const FILTERED_IMAGE_COUNT = 5;
const FILTERED_IMAGE_HEIGHT = 0;
const FILTERED_IMAGE_WIDTH = 0;

chrome.runtime.sendMessage({ todo: "showPageAction" });

// Add JavaScript for content that is already on the tab e.g. accessing existing page elements

window.addEventListener('load', (event) => {
    var allImages = document.querySelectorAll("img");
    var filteredImages = [];

    for (var i = 0; i < allImages.length; i++) {
        if (filteredImages.length >= FILTERED_IMAGE_COUNT) {
            break;
        }

        if ((allImages[i].alt == null || allImages[i].alt.length == 0)
            && allImages[i].height > FILTERED_IMAGE_HEIGHT
            && allImages[i].width > FILTERED_IMAGE_WIDTH) {
            filteredImages.push(allImages[i]);
        }
    }

    console.log(filteredImages);

    filteredImages.forEach(element => {
        element.alt = "Generated by The Bigger Picture"
    });
})